import { createTheme } from "@mui/material/styles";
import styled from "styled-components";

export const sx_button = {
  width: {
    xs: 100,
    sm: 175,
    md: 250,
    lg: 250,
    xl: 250,
  },
  mt: 15,
  mb: 5,
  ml: 5,
  mr: 5,
};
export const sx_box = {
  fontSize: {
    xs: 15,
    sm: 20,
    md: 30,
    lg: 30,
    xl: 30,
  },
};
export const theme = createTheme({
  palette: {
    backButton: {
      main: "#00000",
      contrastText: "#fff",
    },
    button: {
      main: "#f26665",
      contrastText: "#fff",
    },
  },
});
export const AppContainer = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-decoration: none;
`;
export const Box = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  width: 200px;
  height: 200px;
  background-color: white;
  border: 2px dashed #000;
`;

export const cities = [
  "Przysucha",
  "Nieborowice",
  "Żernica",
  "Rusinów",
  "Wieniawa",
  "Pionki",
  "Gózd",
  "Iłża",
  "Jastrzębia",
  "Jedlińsk",
  "Jedlnia",
  "Kowala",
  "Przytyk",
  "Skaryszew",
  "Wolanów",
  "Chlewiska",
  "Jastrząb",
  "Mirów",
  "Orońsko",
  "Szydłowiec",
  "Kazanów",
  "Policzna",
  "Przyłęk",
  "Tczów",
  "Zwoleń",
  "Radom",
  "Warszawa",
  "Bemowo",
  "Białołęka",
  "Mokotów",
  "Ochota",
  "Praga",
  "Rembertów",
  "Śródmieście",
  "Targówek",
  "Ursus",
  "Ursynów",
  "Wawer",
  "Wesoła",
  "Wilanów",
  "Włochy",
  "Wola",
  "Żoliborz",
  "Garwolin",
  "Łaskarzew",
  "Borowie",
  "Maciejowice",
  "Miastków Kościelny",
  "Parysów",
  "Pilawa",
  "Sobolew",
  "Trojanów",
  "Wilga",
  "Żelechów",
  "Legionowo",
  "Nieporęt",
  "Serock",
  "Wieliszew",
  "Mińsk Mazowiecki",
  "Sulejówek",
  "Cegłów",
  "Dębe Wielkie",
  "Halinów",
  "Jakubów",
  "Kałuszyn",
  "Latowicz",
  "Mrozy",
  "Siennica",
  "Stanisławów",
  "Nowy Dwór Mazowiecki",
  "Czosnów",
  "Leoncin",
  "Nasielsk",
  "Pomiechówek",
  "Zakroczym",
  "Otwock",
  "Celestynów",
  "Karczew",
  "Kołbiel",
  "Osieck",
  "Sobienie",
  "Wiązowna",
  "Kobyłka",
  "Marki",
  "Ząbki",
  "Zielonka",
  "Dąbrówka",
  "Jadów",
  "Klembów",
  "Radzymin",
  "Strachówka",
  "Tłuszcz",
  "Wołomin",
  "Milanówek",
  "Podkowa Leśna",
  "Grodzisk Mazowiecki",
  "Jaktorów",
  "Żabia Wola",
  "Belsk Duży",
  "Błędów",
  "Chynów",
  "Goszczyn",
  "Grójec",
  "Jasieniec",
  "Mogielnica",
  "Nowe Miasto nad Pilicą",
  "Pniewy",
  "Tarczyn",
  "Warka",
  "Góra Kalwaria",
  "Konstancin-Jeziorna",
  "Lesznowola",
  "Piaseczno",
  "Prażmów",
  "Piastów",
  "Pruszków",
  "Brwinów",
  "Nadarzyn",
  "Raszyn",
  "Sochaczew",
  "Brochów",
  "Iłów",
  "Młodzieszyn",
  "Nowa Sucha",
  "Rybno",
  "Teresin",
  "Błonie",
  "Izabelin",
  "Kampinos",
  "Leszno",
  "Łomianki",
  "Ożarów Mazowiecki",
  "Stare Babice",
  "Żyrardów",
  "Mszczonów",
  "Puszcza Mariańska",
  "Radziejowice",
  "Wiskitki",
  "Brzeg",
  "Skarbimierz",
  "Grodków",
  "Lewin Brzeski",
  "Lubsza",
  "Byczyna",
  "Kluczbork",
  "Lasowice Wielkie",
  "Wołczyn",
  "Domaszowice",
  "Namysłów",
  "Pokój",
  "Świerczów",
  "Głuchołazy",
  "Kamiennik",
  "Korfantów",
  "Łambinowice",
  "Nysa",
  "Otmuchów",
  "Paczków",
  "Pakosławice",
  "Skoroszyce",
  "Głogówek",
  "Prudnik",
  "Baborów",
  "Branice",
  "Głubczyce",
  "Kietrz",
  "Kędzierzyn-Koźle",
  "Bierawa",
  "Cisek",
  "Pawłowiczki",
  "Polska Cerekiew",
  "Reńska Wieś",
  "Gogolin",
  "Krapkowice",
  "Strzeleczki",
  "Walce",
  "Zdzieszowice",
  "Dobrodzień",
  "Gorzów Śląski",
  "Praszka",
  "Rudniki",
  "Zębowice",
  "Chrząstowice",
  "Dobrzeń Wielki",
  "Komprachcice",
  "Łubniany",
  "Murów",
  "Niemodlin",
  "Ozimek",
  "Popielów",
  "Prószków",
  "Tarnów Opolski",
  "Tułowice",
  "Turawa",
  "Izbicko",
  "Jemielnica",
  "Kolonowskie",
  "Leśnica",
  "Strzelce Opolskie",
  "Zawadzkie",
  "Opole",
  "Baligród",
  "Cisna",
  "Czarna",
  "Lesko",
  "Lutowiska",
  "Olszanica",
  "Solina",
  "Ustrzyki Dolne",
  "Brzozów",
  "Domaradz",
  "Dydnia",
  "Haczów",
  "Jasienica Rosielna",
  "Nozdrzec",
  "Jasło",
  "Brzyska",
  "Dębowiec",
  "Kołaczyce",
  "Krempna",
  "Nowy Żmigród",
  "Osiek Jasielski",
  "Skołyszyn",
  "Tarnowiec",
  "Chorkówka",
  "Dukla",
  "Iwonicz-Zdrój",
  "Jedlicze",
  "Korczyna",
  "Krościenko Wyżne",
  "Miejsce Piastowe",
  "Rymanów",
  "Wojaszówka",
  "Sanok",
  "Besko",
  "Bukowsko",
  "Komańcza",
  "Tyrawa Wołoska",
  "Zagórz",
  "Zarszyn",
  "Krosno",
  "Jarosław",
  "Radymno",
  "Chłopice",
  "Laszki",
  "Pawłosiów",
  "Pruchnik",
  "Rokietnica",
  "Roźwienica",
  "Wiązownica",
  "Lubaczów",
  "Cieszanów",
  "Horyniec",
  "Narol",
  "Oleszyce",
  "Stary Dzików",
  "Wielkie Oczy",
  "Bircza",
  "Dubiecko",
  "Fredropol",
  "Krasiczyn",
  "Krzywcza",
  "Medyka",
  "Orły",
  "Przemyśl",
  "Stubno",
  "Żurawica",
  "Przeworsk",
  "Adamówka",
  "Gać",
  "Jawornik Polski",
  "Kańczuga",
  "Sieniawa",
  "Tryńcza",
  "Zarzecze",
  "Cmolas",
  "Kolbuszowa",
  "Majdan Królewski",
  "Niwiska",
  "Raniżów",
  "Dzikowiec",
  "Łańcut",
  "Markowa",
  "Rakszawa",
  "Żołynia",
  "Iwierzyce",
  "Ostrów",
  "Ropczyce",
  "Sędziszów Małopolski",
  "Wielopole Skrzyńskie",
  "Dynów",
  "Błażowa",
  "Boguchwała",
  "Chmielnik",
  "Głogów Małopolski",
  "Hyżne",
  "Lubenia",
  "Sokołów Małopolski",
  "Świlcza",
  "Trzebownisko",
  "Tyczyn",
  "Czudec",
  "Frysztak",
  "Niebylec",
  "Strzyżów",
  "Rzeszów",
  "Dębica",
  "Brzostek",
  "Jodłowa",
  "Pilzno",
  "Żyraków",
  "Leżajsk",
  "Grodzisko Dolne",
  "Kuryłówka",
  "Nowa Sarzyna",
  "Mielec",
  "Borowa",
  "Czermin",
  "Gawłuszowice",
  "Padew Narodowa",
  "Przecław",
  "Radomyśl Wielki",
  "Tuszów Narodowy",
  "Wadowice Górne",
  "Harasiuki",
  "Jarocin",
  "Jeżowe",
  "Krzeszów",
  "Nisko",
  "Rudnik nad Sanem",
  "Ulanów",
  "Stalowa Wola",
  "Bojanów",
  "Pysznica",
  "Radomyśl nad Sanem",
  "Zaklików",
  "Zaleszany",
  "Baranów Sandomierski",
  "Gorzyce",
  "Grębów",
  "Nowa Dęba",
  "Tarnobrzeg",
  "Choroszcz",
  "Czarna Białostocka",
  "Dobrzyniewo Duże",
  "Gródek",
  "Juchnowiec Kościelny",
  "Łapy",
  "Michałowo",
  "Supraśl",
  "Suraż",
  "Turośń Kościelna",
  "Tykocin",
  "Wasilków",
  "Zabłudów",
  "Zawady",
  "Dąbrowa Białostocka",
  "Janów",
  "Korycin",
  "Krynki",
  "Kuźnica",
  "Nowy Dwór",
  "Sidra",
  "Sokółka",
  "Suchowola",
  "Szudziałowo",
  "Białystok",
  "Bielsk Podlaski",
  "Brańsk",
  "Boćki",
  "Orla",
  "Rudka",
  "Wyszki",
  "Hajnówka",
  "Białowieża",
  "Czeremcha",
  "Czyże",
  "Dubicze Cerkiewne",
  "Kleszczele",
  "Narew",
  "Narewka",
  "Kolno",
  "Grabowo",
  "Mały Płock",
  "Stawiski",
  "Turośl",
  "Jedwabne",
  "Łomża",
  "Miastkowo",
  "Nowogród",
  "Piątnica",
  "Przytuły",
  "Śniadowo",
  "Wizna",
  "Zbójna",
  "Siemiatycze",
  "Drohiczyn",
  "Dziadkowice",
  "Grodzisk",
  "Mielnik",
  "Milejczyce",
  "Nurzec",
  "Perlejewo",
  "Wysokie Mazowieckie",
  "Ciechanowiec",
  "Czyżew",
  "Klukowo",
  "Kobylin",
  "Kulesze Kościelne",
  "Nowe Piekuty",
  "Sokoły",
  "Szepietowo",
  "Zambrów",
  "Kołaki Kościelne",
  "Rutki",
  "Szumowo",
  "Augustów",
  "Bargłów Kościelny",
  "Lipsk",
  "Nowinka",
  "Płaska",
  "Sztabin",
  "Grajewo",
  "Radziłów",
  "Rajgród",
  "Szczuczyn",
  "Goniądz",
  "Jasionówka",
  "Jaświły",
  "Knyszyn",
  "Krypno",
  "Mońki",
  "Trzcianne",
  "Sejny",
  "Giby",
  "Krasnopol",
  "Puńsk",
  "Bakałarzewo",
  "Filipów",
  "Jeleniewo",
  "Przerośl",
  "Raczki",
  "Rutka",
  "Suwałki",
  "Szypliszki",
  "Wiżajny",
  "Pruszcz Gdański",
  "Cedry Wielkie",
  "Kolbudy",
  "Przywidz",
  "Pszczółki",
  "Suchy Dąb",
  "Trąbki Wielkie",
  "Chmielno",
  "Kartuzy",
  "Przodkowo",
  "Sierakowice",
  "Somonino",
  "Sulęczyno",
  "Żukowo",
  "Krynica Morska",
  "Nowy Dwór Gdański",
  "Ostaszewo",
  "Stegna",
  "Sztutowo",
  "Hel",
  "Jastarnia",
  "Puck",
  "Władysławowo",
  "Kosakowo",
  "Krokowa",
  "Reda",
  "Rumia",
  "Wejherowo",
  "Choczewo",
  "Gniewino",
  "Linia",
  "Luzino",
  "Łęczyce",
  "Szemud",
  "Borzytuchom",
  "Bytów",
  "Czarna Dąbrówka",
  "Kołczygłowy",
  "Lipnica",
  "Miastko",
  "Parchowo",
  "Studzienice",
  "Trzebielino",
  "Tuchomie",
  "Chojnice",
  "Brusy",
  "Czersk",
  "Konarzyny",
  "Człuchów",
  "Czarne",
  "Debrzno",
  "Koczała",
  "Przechlewo",
  "Rzeczenica",
  "Lębork",
  "Łeba",
  "Cewice",
  "Nowa Wieś Lęborska",
  "Wicko",
  "Ustka",
  "Damnica",
  "Dębnica Kaszubska",
  "Główczyce",
  "Kępice",
  "Kobylnica",
  "Potęgowo",
  "Słupsk",
  "Smołdzino",
  "Kościerzyna",
  "Dziemiany",
  "Karsin",
  "Liniewo",
  "Lipusz",
  "Nowa Karczma",
  "Stara Kiszewa",
  "Kwidzyn",
  "Gardeja",
  "Prabuty",
  "Ryjewo",
  "Sadlinki",
  "Malbork",
  "Dzierzgoń",
  "Lichnowy",
  "Mikołajki Pomorskie",
  "Miłoradz",
  "Nowy Staw",
  "Stare Pole",
  "Stary Dzierzgoń",
  "Stary Targ",
  "Sztum",
  "Czarna Woda",
  "Skórcz",
  "Starogard Gdański",
  "Bobowo",
  "Kaliska",
  "Lubichowo",
  "Osieczna",
  "Skarszewy",
  "Smętowo Graniczne",
  "Zblewo",
  "Tczew",
  "Gniew",
  "Morzeszczyn",
  "Pelplin",
  "Subkowy",
  "Gdańsk",
  "Gdynia",
  "Sopot",
  "Szczyrk",
  "Bestwina",
  "Buczkowice",
  "Czechowice-Dziedzice",
  "Jasienica",
  "Jaworze",
  "Kozy",
  "Porąbka",
  "Wilamowice",
  "Wilkowice",
  "Cieszyn",
  "Ustroń",
  "Wisła",
  "Brenna",
  "Chybie",
  "Goleszów",
  "Hażlach",
  "Istebna",
  "Skoczów",
  "Strumień",
  "Zebrzydowice",
  "Żywiec",
  "Gilowice",
  "Jeleśnia",
  "Koszarawa",
  "Lipowa",
  "Łękawica",
  "Łodygowice",
  "Milówka",
  "Radziechowy",
  "Rajcza",
  "Ślemień",
  "Świnna",
  "Ujsoły",
  "Węgierska Górka",
  "Bielsko-Biała",
  "Lubliniec",
  "Boronów",
  "Ciasna",
  "Herby",
  "Kochanowice",
  "Koszęcin",
  "Pawonków",
  "Woźniki",
  "Kalety",
  "Miasteczko Śląskie",
  "Radzionków",
  "Tarnowskie Góry",
  "Krupski Młyn",
  "Ożarowice",
  "Świerklaniec",
  "Tworóg",
  "Zbrosławice",
  "Bytom",
  "Piekary Śląskie",
  "Blachownia",
  "Dąbrowa Zielona",
  "Kamienica Polska",
  "Kłomnice",
  "Koniecpol",
  "Konopiska",
  "Kruszyna",
  "Lelów",
  "Mstów",
  "Mykanów",
  "Olsztyn",
  "Poczesna",
  "Przyrów",
  "Rędziny",
  "Starcza",
  "Kłobuck",
  "Krzepice",
  "Lipie",
  "Miedźno",
  "Opatów",
  "Panki",
  "Popów",
  "Przystajń",
  "Wręczyca Wielka",
  "Myszków",
  "Koziegłowy",
  "Niegowa",
  "Poraj",
  "Żarki",
  "Częstochowa",
  "Knurów",
  "Pyskowice",
  "Gierałtowice",
  "Pilchowice",
  "Rudziniec",
  "Sośnicowice",
  "Toszek",
  "Wielowieś",
  "Gliwice",
  "Zabrze",
  "Chorzów",
  "Katowice",
  "Mysłowice",
  "Ruda Śląska",
  "Siemianowice Śląskie",
  "Świętochłowice",
  "Racibórz",
  "Kornowac",
  "Krzanowice",
  "Krzyżanowice",
  "Kuźnia Raciborska",
  "Nędza",
  "Pietrowice Wielkie",
  "Czerwionka-Leszczyny",
  "Gaszowice",
  "Jejkowice",
  "Lyski",
  "Świerklany",
  "Pszów",
  "Radlin",
  "Rydułtowy",
  "Wodzisław Śląski",
  "Godów",
  "Lubomia",
  "Marklowice",
  "Mszana",
  "Jastrzębie-Zdrój",
  "Rybnik",
  "Żory",
  "Będzin",
  "Czeladź",
  "Wojkowice",
  "Mierzęcice",
  "Psary",
  "Siewierz",
  "Poręba",
  "Zawiercie",
  "Irządze",
  "Kroczyce",
  "Łazy",
  "Ogrodzieniec",
  "Pilica",
  "Szczekociny",
  "Włodowice",
  "Żarnowiec",
  "Dąbrowa Górnicza",
  "Jaworzno",
  "Sosnowiec",
  "Łaziska Górne",
  "Mikołów",
  "Orzesze",
  "Ornontowice",
  "Wyry",
  "Goczałkowice",
  "Kobiór",
  "Miedźna",
  "Pawłowice",
  "Pszczyna",
  "Suszec",
  "Bieruń",
  "Imielin",
  "Lędziny",
  "Bojszowy",
  "Chełm Śląski",
  "Tychy",
  "Bieliny",
  "Bodzentyn",
  "Chęciny",
  "Daleszyce",
  "Górno",
  "Łopuszno",
  "Masłów",
  "Miedziana Góra",
  "Mniów",
  "Morawica",
  "Nowa Słupia",
  "Piekoszów",
  "Pierzchnica",
  "Raków",
  "Sitkówka",
  "Strawczyn",
  "Zagnańsk",
  "Fałków",
  "Gowarczów",
  "Końskie",
  "Radoszyce",
  "Ruda Maleniecka",
  "Smyków",
  "Stąporków",
  "Ostrowiec Świętokrzyski",
  "Bałtów",
  "Bodzechów",
  "Ćmielów",
  "Kunów",
  "Waśniów",
  "Skarżysko-Kamienna",
  "Bliżyn",
  "Łączna",
  "Skarżysko Kościelne",
  "Suchedniów",
  "Starachowice",
  "Mirzec",
  "Pawłów",
  "Wąchock",
  "Kielce",
  "Busko-Zdrój",
  "Gnojno",
  "Nowy Korczyn",
  "Pacanów",
  "Solec",
  "Stopnica",
  "Tuczępy",
  "Wiślica",
  "Imielno",
  "Jędrzejów",
  "Małogoszcz",
  "Nagłowice",
  "Oksa",
  "Sędziszów",
  "Sobków",
  "Wodzisław",
  "Bejsce",
  "Kazimierza Wielka",
  "Opatowiec",
  "Skalbmierz",
  "Baćkowice",
  "Iwaniska",
  "Lipnik",
  "Ożarów",
  "Sadowie",
  "Tarłów",
  "Wojciechowice",
  "Działoszyce",
  "Kije",
  "Michałów",
  "Pińczów",
  "Złota",
  "Sandomierz",
  "Dwikozy",
  "Klimontów",
  "Koprzywnica",
  "Łoniów",
  "Obrazów",
  "Samborzec",
  "Wilczyce",
  "Zawichost",
  "Bogoria",
  "Połaniec",
  "Rytwiany",
  "Staszów",
  "Szydłów",
  "Kluczewsko",
  "Krasocin",
  "Moskorzew",
  "Secemin",
  "Włoszczowa",
  "Braniewo",
  "Frombork",
  "Lelkowo",
  "Pieniężno",
  "Płoskinia",
  "Wilczęta",
  "Działdowo",
  "Iłowo",
  "Lidzbark",
  "Płośnica",
  "Elbląg",
  "Godkowo",
  "Gronowo Elbląskie",
  "Markusy",
  "Milejewo",
  "Młynary",
  "Pasłęk",
  "Rychliki",
  "Tolkmicko",
  "Iława",
  "Lubawa",
  "Kisielice",
  "Susz",
  "Zalewo",
  "Nowe Miasto Lubawskie",
  "Biskupiec",
  "Grodziczno",
  "Kurzętnik",
  "Ostróda",
  "Dąbrówno",
  "Grunwald",
  "Łukta",
  "Małdyty",
  "Miłakowo",
  "Miłomłyn",
  "Morąg",
  "Ełk",
  "Kalinowo",
  "Prostki",
  "Stare Juchy",
  "Giżycko",
  "Banie Mazurskie",
  "Budry",
  "Kruklanki",
  "Miłki",
  "Pozezdrze",
  "Ryn",
  "Węgorzewo",
  "Wydminy",
  "Dubeninki",
  "Gołdap",
  "Kowale Oleckie",
  "Olecko",
  "Świętajno",
  "Wieliczki",
  "Biała Piska",
  "Orzysz",
  "Pisz",
  "Ruciane-Nida",
  "Bartoszyce",
  "Górowo Iławeckie",
  "Bisztynek",
  "Sępopol",
  "Kętrzyn",
  "Barciany",
  "Korsze",
  "Reszel",
  "Srokowo",
  "Lidzbark Warmiński",
  "Kiwity",
  "Lubomino",
  "Orneta",
  "Mrągowo",
  "Mikołajki",
  "Piecki",
  "Sorkwity",
  "Janowiec Kościelny",
  "Janowo",
  "Kozłowo",
  "Nidzica",
  "Barczewo",
  "Dobre Miasto",
  "Dywity",
  "Gietrzwałd",
  "Jeziorany",
  "Jonkowo",
  "Olsztynek",
  "Purda",
  "Stawiguda",
  "Świątki",
  "Szczytno",
  "Dźwierzuty",
  "Jedwabno",
  "Pasym",
  "Rozogi",
  "Wielbark",
  "Jaraczewo",
  "Kotlin",
  "Żerków",
  "Blizanów",
  "Ceków",
  "Godziesze Wielkie",
  "Koźminek",
  "Lisków",
  "Mycielin",
  "Opatówek",
  "Stawiszyn",
  "Szczytniki",
  "Żelazków",
  "Bralin",
  "Kępno",
  "Łęka Opatowska",
  "Perzów",
  "Rychtal",
  "Trzcinica",
  "Koźmin Wielkopolski",
  "Krotoszyn",
  "Rozdrażew",
  "Ostrów Wielkopolski",
  "Nowe Skalmierzyce",
  "Odolanów",
  "Przygodzice",
  "Raszków",
  "Sieroszewice",
  "Sośnie",
  "Czajków",
  "Doruchów",
  "Grabów nad Prosną",
  "Kobyla Góra",
  "Kraszewice",
  "Mikstat",
  "Ostrzeszów",
  "Chocz",
  "Dobrzyca",
  "Gizałki",
  "Gołuchów",
  "Pleszew",
  "Kalisz",
  "Gniezno",
  "Czerniejewo",
  "Kiszkowo",
  "Kłecko",
  "Łubowo",
  "Mieleszyn",
  "Niechanowo",
  "Trzemeszno",
  "Witkowo",
  "Koło",
  "Babiak",
  "Chodów",
  "Grzegorzew",
  "Kościelec",
  "Olszówka",
  "Osiek Mały",
  "Przedecz",
  "Golina",
  "Grodziec",
  "Kazimierz Biskupi",
  "Kleczew",
  "Kramsk",
  "Krzymów",
  "Rychwał",
  "Skulsk",
  "Sompolno",
  "Stare Miasto",
  "Ślesin",
  "Wierzbinek",
  "Wilczyn",
  "Słupca",
  "Lądek",
  "Orchowo",
  "Ostrowite",
  "Powidz",
  "Strzałkowo",
  "Zagórów",
  "Turek",
  "Brudzew",
  "Kawęczyn",
  "Malanów",
  "Przykona",
  "Tuliszków",
  "Władysławów",
  "Kołaczkowo",
  "Miłosław",
  "Nekla",
  "Pyzdry",
  "Września",
  "Konin",
  "Borek Wielkopolski",
  "Gostyń",
  "Krobia",
  "Pępowo",
  "Pogorzela",
  "Poniec",
  "Granowo",
  "Grodzisk Wielkopolski",
  "Kamieniec",
  "Rakoniewice",
  "Wielichowo",
  "Kościan",
  "Czempiń",
  "Krzywiń",
  "Śmigiel",
  "Krzemieniewo",
  "Rydzyna",
  "Święciechowa",
  "Wijewo",
  "Włoszakowice",
  "Chrzypsko Wielkie",
  "Kwilcz",
  "Międzychód",
  "Sieraków",
  "Kuślin",
  "Lwówek",
  "Miedzichowo",
  "Nowy Tomyśl",
  "Opalenica",
  "Zbąszyń",
  "Bojanowo",
  "Jutrosin",
  "Miejska Górka",
  "Pakosław",
  "Rawicz",
  "Przemęt",
  "Siedlec",
  "Wolsztyn",
  "Chodzież",
  "Budzyń",
  "Margonin",
  "Szamocin",
  "Czarnków",
  "Drawsko",
  "Krzyż Wielkopolski",
  "Lubasz",
  "Połajewo",
  "Trzcianka",
  "Wieleń",
  "Piła",
  "Białośliwie",
  "Kaczory",
  "Łobżenica",
  "Miasteczko Krajeńskie",
  "Ujście",
  "Wyrzysk",
  "Wysoka",
  "Wągrowiec",
  "Damasławek",
  "Gołańcz",
  "Mieścisko",
  "Skoki",
  "Wapno",
  "Złotów",
  "Jastrowie",
  "Krajenka",
  "Lipka",
  "Okonek",
  "Tarnówka",
  "Oborniki",
  "Rogoźno",
  "Ryczywół",
  "Luboń",
  "Puszczykowo",
  "Buk",
  "Czerwonak",
  "Dopiewo",
  "Kleszczewo",
  "Komorniki",
  "Kostrzyn",
  "Kórnik",
  "Mosina",
  "Murowana Goślina",
  "Pobiedziska",
  "Stęszew",
  "Suchy Las",
  "Swarzędz",
  "Tarnowo Podgórne",
  "Obrzycko",
  "Duszniki-Zdrój",
  "Kaźmierz",
  "Ostroróg",
  "Szamotuły",
  "Wronki",
  "Dominowo",
  "Krzykosy",
  "Nowe Miasto nad Wartą",
  "Środa Wielkopolska",
  "Zaniemyśl",
  "Dolsk",
  "Książ Wielkopolski",
  "Śrem",
  "Poznań",
  "Białogard",
  "Karlino",
  "Tychowo",
  "Czaplinek",
  "Drawsko Pomorskie",
  "Kalisz Pomorski",
  "Ostrowice",
  "Wierzchowo",
  "Złocieniec",
  "Kołobrzeg",
  "Dygowo",
  "Gościno",
  "Rymań",
  "Siemyśl",
  "Ustronie Morskie",
  "Będzino",
  "Biesiekierz",
  "Bobolice",
  "Manowo",
  "Mielno",
  "Polanów",
  "Sianów",
  "Świeszyno",
  "Darłowo",
  "Malechowo",
  "Postomino",
  "Szczecinek",
  "Barwice",
  "Biały Bór",
  "Borne Sulinowo",
  "Grzmiąca",
  "Świdwin",
  "Brzeżno",
];